name: "HomeLAI VOSK MQTT Server"
description: "Servidor VOSK MQTT de HomeLAI para domotica."
version: "0.1.0"
slug: "homelai_vosk_mqtt"
init: false
arch:
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
host_network: true
options:
  port: 8000
  data_path: "/data/homelai"
schema:
  port: int
  data_path: str
map:
  - "config:rw"
  - "share:rw"
ports: {}
ports_description: {}
