name: "HomeLAI DIET NLU"
description: "Servidor NLU DIET (FastAPI) de HomeLAI para tareas domotica."
version: "0.1.0"
slug: "homelai_diet"
init: false
arch:
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
host_network: true
options:
  port: 8000
  data_path: "/data/diet"
schema:
  port: int
  data_path: str
map:
  - "config:rw"
  - "share:rw"
ports: {}
ports_description: {}
